import { prisma } from '@/lib/prisma';
import { normalizeQuery, slugify } from '@/lib/slug';
import {
  getDestinationBySlug,
  fullDestinationInclude,
  type FullDestination,
} from '@/features/destinations/service';
import { generateDestinationContent } from '@/features/search/generate';
import type { DestinationContent } from '@/features/search/content-schema';

export interface SearchResult {
  destination: FullDestination;
  /** true when served from the database, false when freshly generated by AI. */
  cached: boolean;
}

function clampRating(value: number): number {
  return Math.min(5, Math.max(1, Math.round(value)));
}

/** Persist freshly-generated AI content as a new Destination + children. */
async function persistDestinationContent(
  content: DestinationContent,
): Promise<FullDestination> {
  const slug = slugify(content.slug || content.name);

  return prisma.destination.create({
    data: {
      slug,
      name: content.name,
      city: content.city,
      region: content.region,
      country: content.country,
      summary: content.summary,
      description: content.description,
      bestSeason: content.bestSeason,
      source: 'AI_GENERATED',
      attractions: { create: content.attractions },
      hiddenGems: { create: content.hiddenGems },
      heritageStory: { create: content.heritageStory },
      culturalExperiences: {
        create: content.culturalExperiences.map((e) => ({
          ...e,
          authenticityRating: clampRating(e.authenticityRating),
        })),
      },
      localFood: { create: content.localFood },
      travelTips: { create: content.travelTips },
    },
    include: fullDestinationInclude,
  });
}

/**
 * Core search flow:
 *   normalize query → look up by slug (cache) → hit returns instantly →
 *   miss generates via AI → persist → return. Records a search-history row for
 *   the user either way.
 */
export async function searchDestination(params: {
  query: string;
  userId: string;
}): Promise<SearchResult> {
  const normalized = normalizeQuery(params.query);
  const querySlug = slugify(params.query);

  // 1. Cache hit on the query slug.
  let destination = await getDestinationBySlug(querySlug);
  let cached = true;

  // 2. Cache miss → generate, then guard against a differing canonical slug.
  if (!destination) {
    const content = await generateDestinationContent(params.query);
    const canonicalSlug = slugify(content.slug || content.name);

    const existing =
      canonicalSlug !== querySlug
        ? await getDestinationBySlug(canonicalSlug)
        : null;

    destination = existing ?? (await persistDestinationContent(content));
    cached = existing != null;
  }

  // 3. Record history (never blocks the response on failure).
  await prisma.searchHistory
    .create({
      data: {
        userId: params.userId,
        query: params.query,
        normalizedQuery: normalized,
        destinationId: destination.id,
      },
    })
    .catch(() => undefined);

  return { destination, cached };
}
